services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    command: >
      uvicorn src.api.app:app --host 0.0.0.0 --port 4000 --reload
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend

  database:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: terminal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - terminal_database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "terminal_db"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s

volumes:
  terminal_database:

networks:
  terminal_network:
    driver: bridge
