services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    command: >
      uvicorn src.app:app --host 0.0.0.0 --port 4000 --reload
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
